CREATE TABLE IF NOT EXISTS UNIDADES(
    COD VARCHAR(6) PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    TIPO VARCHAR(45) NOT NULL,
    FORNECEDOR VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS FATURAS(
    NF VARCHAR(9) PRIMARY KEY,
    VALOR_BOLETO FLOAT NOT NULL,
    VALOR_TOTAL FLOAT NOT NULL,
    EMISSAO VARCHAR(10) NOT NULL,
    VENCIMENTO VARCHAR(10) NOT NULL,
    UNIDADE_COD VARCHAR(6) NOT NULL,
    FOREIGN KEY (UNIDADE_COD) REFERENCES UNIDADES(COD)
);
