CREATE TABLE IF NOT EXISTS UNIDADES(
    COD VARCHAR(6) PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    TIPO VARCHAR(45) NOT NULL,
    FORNECEDOR VARCHAR(45) NOT NULL
);

CREATE TABLE IF NOT EXISTS FATURAS(
    NF VARCHAR(9) PRIMARY KEY,
    VALOR_BOLETO FLOAT NOT NULL,
    VALOR_TOTAL FLOAT NOT NULL,
    EMISSAO DATE NOT NULL,
    VENCIMENTO DATE NOT NULL,
    UNIDADE_COD VARCHAR(6) NOT NULL,
    FOREIGN KEY (UNIDADE_COD) REFERENCES UNIDADES(COD)
);

INSERT INTO UNIDADES (COD, NOME, TIPO, FORNECEDOR) VALUES
('252310', 'HOFFMANN', 'BENEFICIO', 'TICKET LOG - VT'),
('247133', 'IMPACTO', 'BENEFICIO', 'TICKET LOG - VT'),
('247142', 'RENTOKIL PE', 'BENEFICIO', 'TICKET LOG - VT'),
('247147', 'RENTOKIL RJ', 'BENEFICIO', 'TICKET LOG - VT'),
('247131', 'RENTOKIL RS', 'BENEFICIO', 'TICKET LOG - VT'),
('247132', 'RENTOKIL SP', 'BENEFICIO', 'TICKET LOG - VT'),
('247144', 'UNIAO SUL', 'BENEFICIO', 'TICKET LOG - VT'),
('213639', 'ATIVA', 'TICKET LOG', 'TICKET LOG'),
('213641', 'ECOVEC', 'TICKET LOG', 'TICKET LOG'),
('206337', 'HOFFMANN', 'TICKET LOG', 'TICKET LOG'),
('228518', 'IMPACTO', 'TICKET LOG', 'TICKET LOG'),
('234938', 'PROTECTA AL', 'TICKET LOG', 'TICKET LOG'),
('234942', 'PROTECTA AM', 'TICKET LOG', 'TICKET LOG'),
('233603', 'PROTECTA BA', 'TICKET LOG', 'TICKET LOG'),
('238069', 'PROTECTA CE', 'TICKET LOG', 'TICKET LOG'),
('234943', 'PROTECTA ES', 'TICKET LOG', 'TICKET LOG'),
('234934', 'PROTECTA GO', 'TICKET LOG', 'TICKET LOG'),
('234947', 'PROTECTA MA', 'TICKET LOG', 'TICKET LOG'),
('234945', 'PROTECTA PA', 'TICKET LOG', 'TICKET LOG'),
('234935', 'PROTECTA PB', 'TICKET LOG', 'TICKET LOG'),
('234944', 'PROTECTA PE', 'TICKET LOG', 'TICKET LOG'),
('234946', 'PROTECTA PI', 'TICKET LOG', 'TICKET LOG'),
('234941', 'PROTECTA RN', 'TICKET LOG', 'TICKET LOG'),
('233604', 'PROTECTA SE', 'TICKET LOG', 'TICKET LOG'),
('234937', 'PROTECTA TO', 'TICKET LOG', 'TICKET LOG'),
('213614', 'RENTOKIL DF', 'TICKET LOG', 'TICKET LOG'),
('213603', 'RENTOKIL GO', 'TICKET LOG', 'TICKET LOG'),
('213617', 'RENTOKIL MG', 'TICKET LOG', 'TICKET LOG'),
('213634', 'RENTOKIL PE', 'TICKET LOG', 'TICKET LOG'),
('213629', 'RENTOKIL RJ', 'TICKET LOG', 'TICKET LOG'),
('213623', 'RENTOKIL RS', 'TICKET LOG', 'TICKET LOG'),
('213599', 'RENTOKIL SP', 'TICKET LOG', 'TICKET LOG'),
('213636', 'UNIAO SUL', 'TICKET LOG', 'TICKET LOG'),
('238688', 'RENTOKIL GO', 'TICKET MOBILIDADE', 'EDENRED'),
('238686', 'RENTOKIL PE', 'TICKET MOBILIDADE', 'EDENRED'),
('236886', 'RENTOKIL RJ', 'TICKET MOBILIDADE', 'EDENRED'),
('238758', 'RENTOKIL RS', 'TICKET MOBILIDADE', 'EDENRED'),
('238678', 'RENTOKIL SP', 'TICKET MOBILIDADE', 'EDENRED');

